# Generated by Django 3.0.3 on 2020-03-20 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
